// Form1.Designer.cs
// ============================================================
// This is the WinForms Designer partial class for Form1.
// It is responsible for *creating* and *laying out* UI controls.
//
// Big picture layout:
// - _split: A 2-column TableLayoutPanel
//      - Left side: calculator UI (_left)
//      - Right side: history UI (_right)
//
// Left side (_left) contains:
//  1) _inputs: Quote + optional 2nd input (CH Robinson fee)
//  2) _optionsRow: two checkboxes
//  3) Keypad (BuildKeypad())
//  4) Calculate button
//  5) Bottom row: small YouTube/help button
//
// Right side (_right) contains:
//  1) History title
//  2) DataGridView history table
//
// IMPORTANT NOTE:
// - In most WinForms apps, the Designer file is generated by Visual Studio.
// - You *can* comment it for explanation, but be careful editing structure.
// - Your code calls methods like ApplyModernTheme(), ConfigureHistoryGrid(),
//   AddRightClickMenu(), AttachInputFilters(), BuildKeypad(), StylePrimaryButton(),
//   StyleGhostButton(), SetSecondInputVisible() which live in Form1.cs.
// ============================================================

using System.ComponentModel;   // IContainer, Container
using System.Drawing;          // Font, Color, Size, Padding
using System.Windows.Forms;    // WinForms controls like TextBox, Button, TableLayoutPanel, etc.

namespace Freight_Cost
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// This container holds components that need disposal (like ToolTips).
        /// </summary>
        private IContainer components = null;

        // ============================================================
        // Control Fields
        // ============================================================
        //
        // These are the UI elements on the form. They are fields so:
        // - Other code (Form1.cs) can access them
        // - Event handlers can reference them
        // - State can be read/updated after initialization
        //
        // Naming convention here uses underscores (private fields).
        // ============================================================

        private TextBox _input1;          // Quote input
        private TextBox _input2;          // Optional 2nd input (CH Robinson fee)
        private TextBox _output;          // (Not used in this snippet, but kept as a field)
        private Label _label1;            // Label for input1
        private Label _label2;            // Label for input2
        private Label _historyHeader;     // (Used in Form1.cs for header click behavior)
        private CheckBox _optA;           // Option A checkbox
        private CheckBox _optB;           // Option B checkbox
        private Button _calc;             // Calculate button
        private DataGridView _history;    // History table

        // Layout containers (TableLayoutPanels are easy for “grid” layouts)
        private TableLayoutPanel _split;       // 2-column split: history + calculator
        private TableLayoutPanel _left;        // Left side content
        private TableLayoutPanel _inputs;      // Contains labels + input textboxes
        private TableLayoutPanel _optionsRow;  // Contains checkboxes
        private TableLayoutPanel _bottomRow;   // Contains YouTube button area
        private TableLayoutPanel _right;       // Right side content

        private Button _ytButton;         // Small help button that opens YouTube
        private Label _historyTitle;      // Title label “History”
        private PictureBox _rambo;             // RAMBO

        /// <summary>
        /// Clean up resources being used.
        /// When the form closes, we dispose any components that were created.
        /// </summary>
        /// <param name="disposing">
        /// true if managed resources should be disposed; otherwise false
        /// </param>
        protected override void Dispose(bool disposing)
        {
            // If we're disposing and we have a component container, dispose it
            // (ToolTips and similar components live here)
            if (disposing && (components != null))
            {
                components.Dispose();
            }

            // Base class cleanup
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Initializes all controls, sets properties, and builds the layout.
        /// This is called from the Form1 constructor BEFORE you start wiring events.
        /// </summary>
        private void InitializeComponent()
        {
            // Create the component container first
            components = new Container();

            // Instantiate UI controls (actual objects)
            _input1 = new TextBox();
            _input2 = new TextBox();
            _output = new TextBox();
            _label1 = new Label();
            _label2 = new Label();
            _historyHeader = new Label(); // NOTE: You are not adding this to the UI here;
                                          // it still exists as a field for the code-behind.
            _optA = new CheckBox();
            _optB = new CheckBox();
            _calc = new Button();
            _history = new DataGridView();

            // Instantiate layout containers
            _split = new TableLayoutPanel();
            _left = new TableLayoutPanel();
            _inputs = new TableLayoutPanel();
            _optionsRow = new TableLayoutPanel();
            _bottomRow = new TableLayoutPanel();
            _right = new TableLayoutPanel();

            // Other UI elements
            _ytButton = new Button();
            _rambo = new PictureBox();
            _historyTitle = new Label();

            // Pause layout calculations while we build UI
            // (prevents flicker and speeds initialization)
            SuspendLayout();

            // ============================================================
            // APP WINDOW (Form-level settings)
            // ============================================================

            Text = "M.F. BOYS CALCULATOR";                  // Window title bar text
            Font = new Font("Segoe UI", 10f, FontStyle.Regular); // Default font for child controls
            StartPosition = FormStartPosition.CenterScreen; // Start centered on the screen
            FormBorderStyle = FormBorderStyle.FixedDialog;  // Fixed size dialog style window
            MaximizeBox = false;                            // Disable maximize button
            MinimizeBox = true;                            // Disable minimize button
            ClientSize = new Size(1000, 590);               // Window size (excluding title bar)
            BackColor = AppBackground;                      // Uses theme color from Form1.cs
            ForeColor = TextPrimary;                        // Uses theme color from Form1.cs
            AutoScaleMode = AutoScaleMode.Font;             // Automatically scales with font size

            // ============================================================
            // SPLIT LAYOUT: Left calculator + Right history
            // ============================================================
            //
            // Two columns:
            // - Column 0: fixed width (history panel width)
            // - Column 1: remaining space (calculator area)
            // ============================================================

            _split.Dock = DockStyle.Fill;        // Fill the whole form
            _split.ColumnCount = 2;              // Two columns
            _split.Padding = new Padding(12);    // Outer padding around the whole UI
            _split.BackColor = AppBackground;

            // ColumnStyles define width behavior for each column
            _split.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 460)); // fixed
            _split.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100));  // fill remainder

            // Add the split layout to the form
            Controls.Add(_split);

            // ============================================================
            // LEFT SIDE: Calculator UI
            // ============================================================

            _left.Dock = DockStyle.Fill;
            _left.RowCount = 5;
            _left.BackColor = AppBackground;

            // Define row heights:
            _left.RowStyles.Add(new RowStyle(SizeType.Absolute, 150)); // inputs block
            _left.RowStyles.Add(new RowStyle(SizeType.Absolute, 60));  // options (checkboxes)
            _left.RowStyles.Add(new RowStyle(SizeType.Percent, 100));  // keypad fills remaining space
            _left.RowStyles.Add(new RowStyle(SizeType.Absolute, 55));  // calculate button
            _left.RowStyles.Add(new RowStyle(SizeType.Absolute, 60));  // bottom row (YouTube button)

            // Put the left panel into column 0 of the split
            _split.Controls.Add(_left, 0, 0);

            // ============================================================
            // INPUTS AREA: labels + textboxes
            // ============================================================

            _inputs.Dock = DockStyle.Fill;
            _inputs.RowCount = 4;
            _inputs.ColumnCount = 1;
            _inputs.Padding = new Padding(12);                 // inner padding inside the card
            _inputs.BackColor = CardBackground;                // card look
            _inputs.Margin = new Padding(0, 0, 0, 12);         // space under the card

            // Row heights within the inputs card:
            _inputs.RowStyles.Add(new RowStyle(SizeType.Absolute, 15)); // label1
            _inputs.RowStyles.Add(new RowStyle(SizeType.Absolute, 50)); // input1
            _inputs.RowStyles.Add(new RowStyle(SizeType.Absolute, 17)); // label2
            _inputs.RowStyles.Add(new RowStyle(SizeType.Absolute, 50)); // input2

            // Add inputs card into the left layout row 0
            _left.Controls.Add(_inputs, 0, 0);

            // ---- Label 1 (Quote) ----
            _label1.Text = "Quote (USD)";
            _label1.Dock = DockStyle.Fill;
            _label1.Font = new Font(Font, FontStyle.Bold); // bold label for clarity
            _label1.ForeColor = TextMuted;                 // muted gray text

            // ---- Input 1 (Quote) ----
            _input1.Dock = DockStyle.Fill;
            _input1.Font = new Font(Font.FontFamily, 16f, FontStyle.Regular);   // larger input text
            _input1.TextAlign = HorizontalAlignment.Right;                      // calculator style alignment
            _input1.PlaceholderText = "$0.00";                                  // hint text
            _input1.ShortcutsEnabled = true;                                    // allow Ctrl+C / Ctrl+V etc.

            // Add custom right-click menu and input filtering (from Form1.cs)
            AddRightClickMenu(_input1);
            AttachInputFilters(_input1);

            // ---- Label 2 (CH Robinson fee) ----
            _label2.Text = "Length fee from C.H. Robinson";
            _label2.Dock = DockStyle.Fill;
            _label2.Font = new Font(Font, FontStyle.Bold);
            _label2.ForeColor = TextMuted;

            // ---- Input 2 (CH Robinson fee amount) ----
            _input2.Dock = DockStyle.Fill;
            _input2.Font = new Font(Font.FontFamily, 16f, FontStyle.Regular);
            _input2.TextAlign = HorizontalAlignment.Right;
            _input2.PlaceholderText = "$0.00";
            _input2.ShortcutsEnabled = true;

            // Same custom menu + filters
            AddRightClickMenu(_input2);
            AttachInputFilters(_input2);

            // Add controls into the inputs card table
            _inputs.Controls.Add(_label1, 0, 0);
            _inputs.Controls.Add(_input1, 0, 1);
            _inputs.Controls.Add(_label2, 0, 2);
            _inputs.Controls.Add(_input2, 0, 3);

            // Start with second input hidden (Option B will show it)
            SetSecondInputVisible(false);

            // ============================================================
            // CHECKBOX OPTIONS ROW
            // ============================================================

            _optionsRow.Dock = DockStyle.Fill;
            _optionsRow.ColumnCount = 2;
            _optionsRow.Padding = new Padding(12);
            _optionsRow.BackColor = CardBackground; // another card section
            _optionsRow.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50));
            _optionsRow.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50));

            // Option A: fixed $150 fee if checked (per Form1.cs logic)
            _optA.Text = "Length is 8' to 20'?";
            _optA.Dock = DockStyle.Fill;
            _optA.ForeColor = TextPrimary;

            // Option B: use CH Robinson fee (enables second textbox)
            _optB.Text = "Over 20'?";
            _optB.Dock = DockStyle.Fill;
            _optB.ForeColor = TextPrimary;

            // Place checkboxes into the options row
            _optionsRow.Controls.Add(_optA, 0, 0);
            _optionsRow.Controls.Add(_optB, 1, 0);

            // Add options row into left layout row 1
            _left.Controls.Add(_optionsRow, 0, 1);

            // ============================================================
            // KEYPAD AREA (custom layout built in Form1.cs)
            // ============================================================

            // BuildKeypad() returns a Control (TableLayoutPanel)
            // containing keypad buttons wired to your input logic.
            _left.Controls.Add(BuildKeypad, 0, 2);

            // ============================================================
            // CALCULATE BUTTON
            // ============================================================

            _calc.Text = "Calculate";
            _calc.Dock = DockStyle.Fill;
            _calc.Font = new Font(Font.FontFamily, 12f, FontStyle.Bold);

            // Apply primary styling (blue button)
            StylePrimaryButton(_calc);

            // Add calculate button into left layout row 3
            _left.Controls.Add(_calc, 0, 3);

            // ============================================================
            // BOTTOM ROW: small YouTube/help button
            // ============================================================

            _bottomRow.Dock = DockStyle.Top;
            _bottomRow.ColumnCount = 3;
            _bottomRow.BackColor = AppBackground;

            // Column 0 is fixed size for the icon button,
            // Column 1 spacer
            // Column 2 RAMBO
            _bottomRow.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 60));
            _bottomRow.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100));
            _bottomRow.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 60));

            _ytButton.Text = "🔥";
            _ytButton.Dock = DockStyle.None;
            _ytButton.Size = new Size(40, 40);
            _ytButton.Margin = new Padding(5);

            // Use emoji font so the fire icon renders on Windows
            _ytButton.Font = new Font("Segoe UI Emoji", 15f, FontStyle.Regular);

            // Ghost button styling so it’s subtle / out of the way
            StyleGhostButton(_ytButton);

            // White text makes the emoji stand out on dark background
            _ytButton.ForeColor = Color.White;

            // ToolTip component explains the button on hover
            var tip = new ToolTip();
            tip.SetToolTip(_ytButton, "Open help video (YouTube)");


            //_rambo.Image = Properties.Re
            //try
            //{
            //    if (System.IO.File.Exists("RAMBO.png"))
            //    {
            //        _rambo.Image = Image.FromFile("RAMBO.png");
            //    }
            //}
            //catch
            //{
            //    _rambo.Image = null; // or a default icon if you have one
            //}

            _rambo.Dock = DockStyle.None;
            _rambo.SizeMode = PictureBoxSizeMode.Zoom;
            _rambo.BackColor = AppBackground;



            _bottomRow.Controls.Add(_ytButton, 0, 0);
            _bottomRow.Controls.Add(new Panel { Dock = DockStyle.Fill, BackColor = AppBackground }, 1, 0);
            _bottomRow.Controls.Add(_rambo, 2, 0);

            // Add bottom row into left layout row 4
            _left.Controls.Add(_bottomRow, 0, 4);

            // ============================================================
            // RIGHT SIDE: HISTORY UI
            // ============================================================

            _right.Dock = DockStyle.Fill;
            _right.RowCount = 2;
            _right.ColumnCount = 1;
            _right.BackColor = AppBackground;

            // Row 0: title bar
            // Row 1: history table fills remaining space
            _right.RowStyles.Add(new RowStyle(SizeType.Absolute, 45));
            _right.RowStyles.Add(new RowStyle(SizeType.Percent, 100));

            // Place right panel in column 1 of split
            _split.Controls.Add(_right, 1, 0);

            // History title label at top of history panel
            _historyTitle.Text = "History";
            _historyTitle.Dock = DockStyle.Fill;
            _historyTitle.TextAlign = ContentAlignment.MiddleLeft;
            _historyTitle.Font = new Font(Font.FontFamily, 12f, FontStyle.Bold);
            _historyTitle.ForeColor = TextPrimary;

            _right.Controls.Add(_historyTitle, 0, 0);

            // Configure and add history DataGridView (Form1.cs sets columns/styles)
            ConfigureHistoryGrid();
            _right.Controls.Add(_history, 0, 1);

            // ============================================================
            // Final form tweaks
            // ============================================================

            // Apply theme again (harmless if already applied)
            ApplyModernTheme(this);

            // Pressing Enter triggers Calculate (nice UX)
            AcceptButton = _calc;

            // Resume layout now that controls are set up
            ResumeLayout(false);
        }

        #endregion
    }
}
